version: '3.8'

services:
  centos7-cpython-until:
    container_name: centos7-cpython-until
    image: somikhaylov/centos7-cpython-until
    build:
      dockerfile: Dockerfile.until
      context: .
    volumes:
      - ./test:/opt/test
    stdin_open: true

  centos7-cpython-inc:
    container_name: centos7-cpython-inc
    image: somikhaylov/centos7-cpython-inc
    build:
      dockerfile: Dockerfile.inc
      context: .
    volumes:
      - ./test:/opt/test
    stdin_open: true

  centos7-cpython-new-opcode:
    container_name: centos7-cpython-new-opcode
    image: somikhaylov/centos7-cpython-new-opcode
    build:
      dockerfile: Dockerfile.new_opcode
      context: .
    volumes:
      - ./test:/opt/test
    stdin_open: true